### ISSUE TITLE
JsonReaderException when exceeding stream connection limit

### ISSUE THREAD

**Issue by mfakane** [CoreTweet/CoreTweet#143]
Hi.

I'm using CoreTweet 0.7.2.352 from NuGet on a UWP project.
When connecting to streams (with `SampleAsObservable`, etc), and exceeding the rate limit of streaming apis, CoreTweet attempts to create and throw `TwitterException`, but instead, it fails with `Newtonsoft.Json.JsonReaderException`.

Exception Details:
```
Newtonsoft.Json.JsonReaderException occurred
  HResult=0x80131500
  Message=Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
  Source=<Cannot evaluate the exception source>
  StackTrace:
	at Newtonsoft.Json.JsonTextReader.ParseValue()
	at Newtonsoft.Json.JsonTextReader.Read()
	at Newtonsoft.Json.Linq.JObject.Load(Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Linq.JsonLoadSettings settings)
	at Newtonsoft.Json.Linq.JObject.Parse(string json, Newtonsoft.Json.Linq.JsonLoadSettings settings)
	at CoreTweet.TwitterException.ParseErrors(string json)
	at CoreTweet.TwitterException.Create(CoreTweet.AsyncResponse response)
	at System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<CoreTweet.TwitterException.<Create>d__17>(ref CoreTweet.TwitterException.<Create>d__17 stateMachine)
	at CoreTweet.TwitterException.Create(CoreTweet.AsyncResponse response)
	at CoreTweet.Core.InternalUtils.ResponseCallback.AnonymousMethod__18_0(CoreTweet.AsyncResponse res)
	at System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<CoreTweet.Core.InternalUtils.(ref CoreTweet.Core.InternalUtils.<>c.<<ResponseCallback>b__18_0>d stateMachine)
	at CoreTweet.Core.InternalUtils.ResponseCallback.AnonymousMethod__18_0(CoreTweet.AsyncResponse res)
	at CoreTweet.TaskExtensions.Done.AnonymousMethod__0(System.Threading.Tasks.Task<CoreTweet.AsyncResponse> t)
	at System.Threading.Tasks.ContinuationTaskFromResultTask<CoreTweet.AsyncResponse>.InnerInvoke()
	at System.Threading.Tasks.Task.Execute()
```

At `TwitterException.ParseErrors`, the `json` was `"Exceeded connection limit for user\r\n"`, and from `TwitterException.Create`'s `response`, the status code was 420, and `Content-Type` was `text/html`.

**Comment by mfakane** [comment]
I checked the Exception Settings, and there was a check on `<All Common Language Runtime Exceptions not in this list>`, and it seems that this was the cause of breaking on this exception.
It's completely my fault... I'm very sorry about this.
