### ISSUE TITLE
Immediately failing at hello world example

### ISSUE THREAD

**Issue by EntraptaDev** [CoreTweet/CoreTweet#178]
Right off the bat, I'm failing to authenticate and I cannot figure out why. I've regenerated my consumer key and secret to ensure it's not a fluke. But:

`var session = OAuth.Authorize("theConsumerKey", "theConsumerSecret");`

immediately throws:

`System.Net.WebException was unhandled
  HResult=-2146233079
  Message=The underlying connection was closed: An unexpected error occurred on a send.
  Source=System
  StackTrace:
       at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
       at System.Net.HttpWebRequest.GetRequestStream()
       at CoreTweet.Request.HttpPost(Uri url, String contentType, Byte[] content, String authorizationHeader, ConnectionOptions options)
       at CoreTweet.Request.HttpPost(Uri url, IEnumerable``1 prm, String authorizationHeader, ConnectionOptions options)
       at CoreTweet.OAuth.Authorize(String consumerKey, String consumerSecret, String oauthCallback, ConnectionOptions options)
       at TwitterBlockChainForSheRa.Program.Main(String[] args) in C:\Users\lil Buddy\Documents\Visual Studio 2015\Projects\TwitterBlockChainForSheRa\TwitterBlockChainForSheRa\Program.cs:line 20
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146232800
       Message=Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
       Source=System
       StackTrace:
            at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
            at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
            at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
            at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
            at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
            at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
            at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
            at System.Net.TlsStream.CallProcessAuthentication(Object state)
            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
            at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
            at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
            at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
            at System.Net.ConnectStream.WriteHeaders(Boolean async)
       InnerException: 
            ErrorCode=10054
            HResult=-2147467259
            Message=An existing connection was forcibly closed by the remote host
            NativeErrorCode=10054
            Source=System
            StackTrace:
                 at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
                 at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
            InnerException:`

and if it helps at all, this is the output:
`Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in CoreTweet.dll
`

What in the world am I missing? The "An existing connection was forcibly closed by the remote host," message has me at a loss. I cannot get myself past step one. 

Any help is greatly greatly appreciated.

**Comment by cannorin** [comment]
Looks like a duplicate of #169. Try the solution explained there.

**Comment by azyobuzin** [comment]
Do we need to implement that workaround in CoreTweet?

**Comment by cannorin** [comment]
I think there is no need to do that.

1. A library should not modify a global variable.
2. A library should not modify a global variable, especially when it is related to security. Every developer should be aware of security on writing code.
3. Modifying that variable does not entirely solve the problem. The way to make it use TLS 1.2 really depends on the environment they are working with. See: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

**Comment by EntraptaDev** [comment]
@cannorin thank you so much, that was it! 

Recommendation: Update wiki/docs to include troubleshooting tip. 

Thank you again!
